  const express = require('express');
  const router = express.Router();
  const mongoose = require('mongoose');

  // require('dotenv').config({ path: '../.env'});
  mongoose.connect(process.env.MONGO_URI, {
  serverSelectionTimeoutMS: 5000
})
.then(() => {
  console.log("🚀 MongoDB Connected successfully!");  
  app.listen(process.env.PORT || 3000, () => {
    console.log(`Server running on port ${process.env.PORT || 3000}`);
  });
})
.catch(err => {
  console.error("❌ Critical MongoDB connection failure:", err);
});

  const notebookSchema = new mongoose.Schema({
    title: { type: String, required: true, trim: true },
    author: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    isPublic: { type: Boolean, default: false },
    aiSummary: { type: String , default: "Summary pending..."}, // The 2-line summary generated by Gemini
    
    // The array of up to 10 documents
    documents: [{
      fileName: String,
      fileUrl: String, // The Cloudinary/Supabase link
      fileType: String, // 'pdf', 'text', 'ppt'
      rawText: String // Hidden text extracted for Gemini to read
    }],
    likes: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User', default: 0 }]
  }, { timestamps: true }); // Automatically handles 'createdAt' and 'updatedAt'

  const Notebook = mongoose.model('Notebook', notebookSchema);
  module.exports = Notebook;